version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: contractor-postgres
    environment:
      POSTGRES_DB: contractor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: contractor-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  contractor-app:
    build: .
    container_name: contractor-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contractor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  rabbitmq_data:

